version: '3'

services:
   php-72-apache:
     build:
         context: .
         dockerfile: Dockerfile
     ports:
        - "8080:80"
     volumes:
       - ./domains/com/gene:/var/www:cached
       - ./domains:/opt/domains:cached
     tty: true
